### ISSUE TITLE
Add offline trainer component

### ISSUE THREAD

**Issue by sunya-ch** [sustainable-computing-io/kepler-model-server#100]
This component will allow anyone can easily build a model offline by just inputting the prom_response from the query module that query kepler metrics provided in this Kepler-model-server repository. 

[WIP]

**Comment by rootfs** [comment]
This is great! Looking forward to an easy offline process.

**Comment by sunya-ch** [comment]
closed by https://github.com/sustainable-computing-io/kepler-model-server/pull/104
