### ISSUE TITLE
ModelOutputType inconsistency

### ISSUE THREAD

**Issue by albertaillet** [sustainable-computing-io/kepler-model-server#124]
### Which document would you like to be mentioned?

In `doc/model_output.md` it is stated that "Accordingly, there are 8 output types declared as below."
```python
class ModelOutputType(enum.Enum):
    AbsPower = 1
    AbsModelWeight = 2
    AbsComponentPower = 3
    AbsComponentModelWeight = 4
    DynPower = 5
    DynModelWeight = 6
    DynComponentPower = 7
    DynComponentModelWeight = 8
```
However, when looking at the code in `src/util/train_types.py`, the following code is present:
```python
class ModelOutputType(enum.Enum):
    AbsPower = 1
    DynPower = 2
    XGBoostStandalonePower = 3
```
Later in `src/util/train_types.py`, the ones mentioned in the documentation are used:
```python
def is_weight_output(output_type):
    if output_type == ModelOutputType.AbsModelWeight:
        return True
    if output_type == ModelOutputType.AbsComponentModelWeight:
        return True
    if output_type == ModelOutputType.DynModelWeight:
        return True
    if output_type == ModelOutputType.DynComponentModelWeight:
        return True
    return False
```
Why is this the case?

### Why is this needed?

This is needed as the code is currently inconsistent with the documentation for ModelOutputType.

**Comment by sunya-ch** [comment]
Should be fixed by https://github.com/sustainable-computing-io/kepler-model-server/pull/136
