### ISSUE TITLE
Publish CPU architectural/model accuracy numbers

### ISSUE THREAD

**Issue by stleerh** [sustainable-computing-io/kepler-model-server#126]
### Which document would you like to be mentioned?

It could be in:  
[https://sustainable-computing.io/kepler_model_server/power_estimation/](https://sustainable-computing.io/kepler_model_server/power_estimation/)

### Why is this needed?

Per the discussion on sustainable-computing-io/kepler#828, the plan is to publish the CPU architectural/model accuracy numbers. This will be the first step in validating the power estimation consumption values.

**Comment by rootfs** [comment]
@sunya-ch can you add MAE or MAPE metrics to the published models? Thanks.

**Comment by sunya-ch** [comment]
@rootfs Sure. I will publish that when I add the acpi (platform) model to the kepler-model-db. I just found that the current one is missing acpi. Now fixing it.
This is also related to the issue here: https://github.com/sustainable-computing-io/kepler/issues/877.

**Comment by sunya-ch** [comment]
Blocker:
https://github.com/sustainable-computing-io/kepler-model-server/issues/148
