### ISSUE TITLE
 IsNodePowerModel is displayed with incorrect value

### ISSUE THREAD

**Issue by jiangphcn** [sustainable-computing-io/kepler-model-server#141]
### What happened?

After deploying Kepler side, the IsNodePowerModel is printed with incorrect value. 

```
I0904 12:06:56.482425       1 model.go:176] Model Config NODE_COMPONENTS: {ModelType:EstimatorSidecar ModelOutputType:AbsPower TrainerName: EnergySource:rapl SelectFilter: InitModelURL:https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-db/main/models/Linux-4.15.0-213-generic-x86_64_v0.6/rapl/AbsPower/KubeletOnly/GradientBoostingRegressorTrainer_1.zip InitModelFilepath: IsNodePowerModel:false ContainerFeatureNames:[] NodeFeatureNames:[] SystemMetaDataFeatureNames:[] SystemMetaDataFeatureValues:[]}
```

### What did you expect to happen?

The value of IsNodePowerModel is true, but displayed with false.

### How can we reproduce it (as minimally and precisely as possible)?

- deploy kepler-exporter
- deploy kepler side by applying https://github.com/sustainable-computing-io/kepler-model-server/tree/main/manifests/base

### Kepler image tag

<details>

</details>

### Deployment

- [X] Model server
- [ ] Estimator
- [ ] Online trainer
- [ ] Offline trainer
- [ ] Profiler

### Kepler model server image tag if deployed

<details>
quay.io/sustainable_computing_io/kepler@sha256:3dc0346365b7d874b772bb12c8e2d3ff3e4ce0c28dd0cbf5e3991e1b8a0e9f3c
</details>

### Kepler estimator image tag if deployed

<details>

</details>

### Kepler online trainer image tag if deployed

<details>

</details>

### Kepler offline trainer image tag if deployed

<details>

</details>

### Kepler profiler image tag if deployed

<details>

</details>

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Install tools

<details>

</details>

### Kepler deployment config

<details>

For on kubernetes:
```console
$ KEPLER_NAMESPACE=kepler

# provide kepler configmap
$ kubectl get configmap kepler-cfm -n ${KEPLER_NAMESPACE} 
# paste output here

# provide kepler model server configmap if Kepler Model Server is deployed 
$ kubectl get configmap kepler-model-server-cfm -n ${KEPLER_NAMESPACE} 
# paste output here

# provide kepler deployment description
$ kubectl describe deployment kepler-exporter -n ${KEPLER_NAMESPACE} 
```

For standalone:
# put your Kepler command argument here

</details>

**Comment by sunya-ch** [comment]
@jiangphcn It is needed to change line order for the log in Kepler. Would you like to push PR to fix it?

**Comment by jiangphcn** [comment]
Hi @sunya-ch , yes, i will. Need a bit time to test it.
