### ISSUE TITLE
Make me one of the maintainers.

### ISSUE THREAD

**Issue by marceloamaral** [sustainable-computing-io/kepler-model-server#156]
### What would you like to be added?

I am a maintainer in the main Kepler repository and I would like to become a maintainer in the kepler model server repository too.

### Why is this needed?

As a maintainer I will be able to review and approve PRs.

**Comment by marceloamaral** [comment]
@sunya-ch and @rootfs ^^

**Comment by sunya-ch** [comment]
Done
