### ISSUE TITLE
Integrate Kepler with model server

### ISSUE THREAD

**Issue by husky-parul** [sustainable-computing-io/kepler-model-server#16]
As a developer, I want to use Model server to train power estimate models so that the Kepler can get regression model coefficients and use them to quickly estimate per Pod level energy consumption.

1. Model trainer to query prometheus
2. Model trainer to train power model
3. Model Server exposes coefficients
4. Kepler to retrieve coefficients
5. Kepler uses coefficients
6. Model server and training deployment manifest
7. Document architecture

**Comment by sunya-ch** [comment]
- [x] Querying and online training functionality (cover 1-2) should be  done by  
https://github.com/sustainable-computing-io/kepler-model-server/blob/a13ec978d4e73fa168d7ba3cad7b9cdff2477a50/server/main.py#L142-L156
- [x] Model providing (cover 3) should be done by 
https://github.com/sustainable-computing-io/kepler-model-server/blob/a13ec978d4e73fa168d7ba3cad7b9cdff2477a50/server/model_server.py#L64-L101
- [ ] Kepler integration (cover 4-5) should be done by 
   - https://github.com/sustainable-computing-io/kepler/pull/225
   - https://github.com/sustainable-computing-io/kepler-estimator/pull/5
- [ ] (6.) Manifests and tests are in this PR https://github.com/sustainable-computing-io/kepler-model-server/pull/47    
- [ ] (7.) Check this https://github.com/sustainable-computing-io/kepler-model-server/pull/45
