### ISSUE TITLE
Need to fix mount path for read-only system

### ISSUE THREAD

**Issue by sunya-ch** [sustainable-computing-io/kepler-model-server#160]
### What happened?

Even if some write path is fixed in https://github.com/sustainable-computing-io/kepler-model-server/pull/125, there is still some write path left in relative space and causes the following error. 

```
OSError: [Errno 30] Read-only file system: '/usr/local/src/estimate/../util/../models'
```

```
OSError: [Errno 30] Read-only file system: '/usr/local/src/server/../util/./../models'
```

### What did you expect to happen?

```
> oc get po -n kepler
NAME                                  READY   STATUS    RESTARTS   AGE
kepler-exporter-wxczf                 2/2     Running   0          10s
kepler-model-server-c98f84868-x7qpq   1/1     Running   0          63s
```

### Model server log
```
> oc logs -n kepler kepler-model-server-c98f84868-x7qpq
try downloading archieved pipeline from URL: https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-db/main/models/Linux-4.15.0-213-generic-x86_64_v0.6.zip
<Response [200]>
initial pipeline is loaded to /mnt/models/default
...
get request /model: {'metrics': ['bpf_cpu_time_us', 'bpf_net_tx_irq', 'bpf_net_rx_irq', 'bpf_block_irq', 'cgroupfs_memory_usage_bytes', 'cgroupfs_kernel_memory_usage_bytes', 'cgroupfs_tcp_memory_usage_bytes', 'cgroupfs_cpu_usage_us', 'cgroupfs_system_cpu_usage_us', 'cgroupfs_user_cpu_usage_us', 'cgroupfs_ioread_bytes', 'cgroupfs_iowrite_bytes', 'block_devices_used', 'kubelet_cpu_usage', 'kubelet_memory_bytes', 'block_devices_used', 'cpu_architecture'], 'output_type': 'AbsPower', 'source': 'rapl', 'filter': '', 'trainer_name': ''}
xxx - - [12/Sep/2023 07:32:51] "POST /model HTTP/1.1" 200 -
```

### Estimator log
```
> oc logs kepler-exporter-wxczf -n kepler estimator
set NODE_COMPONENTS_ESTIMATOR to true.
set NODE_COMPONENTS_INIT_URL to https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-db/main/models/Linux-4.15.0-213-generic-x86_64_v0.6/rapl/AbsPower/KubeletOnly/GradientBoostingRegressorTrainer_1.zip.
clean socket
load model from model server:  /mnt/download/rapl/AbsPower
```

### How can we reproduce it (as minimally and precisely as possible)?

Run 

```
OPTS="ESTIMATOR SERVER OPENSHIFT_DEPLOY" make deploy
```

for OpenShift cluster on VPC

### Kepler image tag

<details>

</details>

### Deployment

- [X] Model server
- [X] Estimator
- [ ] Online trainer
- [ ] Offline trainer
- [ ] Profiler

### Kepler model server image tag if deployed

<details>

</details>

### Kepler estimator image tag if deployed

<details>

</details>

### Kepler online trainer image tag if deployed

<details>

</details>

### Kepler offline trainer image tag if deployed

<details>

</details>

### Kepler profiler image tag if deployed

<details>

</details>

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Install tools

<details>

</details>

### Kepler deployment config

<details>

For on kubernetes:
```console
$ KEPLER_NAMESPACE=kepler

# provide kepler configmap
$ kubectl get configmap kepler-cfm -n ${KEPLER_NAMESPACE} 
# paste output here

# provide kepler model server configmap if Kepler Model Server is deployed 
$ kubectl get configmap kepler-model-server-cfm -n ${KEPLER_NAMESPACE} 
# paste output here

# provide kepler deployment description
$ kubectl describe deployment kepler-exporter -n ${KEPLER_NAMESPACE} 
```

For standalone:
# put your Kepler command argument here

</details>

**Comment by marceloamaral** [comment]
Can you write in the `/home` folder. Probably the `/root` folder in the container.
We can just use the bash variable `$HOME`, instead of write in `/usr/local/src`

**Comment by sunya-ch** [comment]
I move everything files to under`/mnt` path in the PR https://github.com/sustainable-computing-io/kepler-model-server/pull/158/commits/13b5abfb930fd36a1f9696c7bf046b5f71f07f21.
So that, later we can simply mount it to other storage separately from default path such as /home on FS.
