### ISSUE TITLE
Support third party metrics in the model server

### ISSUE THREAD

**Issue by LeiZhou-97** [sustainable-computing-io/kepler-model-server#181]
### What would you like to be added?

Support third party metrics in the model server

I go through the source code quickly, the model server seems only support to collect hard-core metrics for training.

What I want to know is if there are any development plans to support this feature in the near future? Thanks!

### Why is this needed?

End-user may have their own special metrics and these metrics are not included in Kepler.

**Comment by sunya-ch** [comment]
[This function](https://github.com/sustainable-computing-io/kepler-model-server/blob/421ab2e553003c0eb5cde2ab45a67fa19ffbdbb7/cmd/main.py#L205) in command tool allows querying metric from prometheus with specific metric prefix.

However, I think we can modify the main src to support that too.
1. We can remove filter of kepler query in the following line to collect all the metric.
https://github.com/sustainable-computing-io/kepler-model-server/blob/421ab2e553003c0eb5cde2ab45a67fa19ffbdbb7/src/train/prom/prom_query.py#L33
The query result will be a mapping from query to the values in the same way we have with the kepler.

2. We need to provide an extension in `feature_to_query` in the same we do for node-level feature.

      https://github.com/sustainable-computing-io/kepler-model-server/blob/421ab2e553003c0eb5cde2ab45a67fa19ffbdbb7/src/train/extractor/extractor.py#L139
    
    
    https://github.com/sustainable-computing-io/kepler-model-server/blob/421ab2e553003c0eb5cde2ab45a67fa19ffbdbb7/src/util/prom_types.py#L45-L50
