### ISSUE TITLE
CurveFit trainer (train model with simple curve fit)

### ISSUE THREAD

**Issue by sunya-ch** [sustainable-computing-io/kepler-model-server#214]
### What would you like to be added?

I would like to add a new trainer class in addition to scikit and xgboost called `curvefit` (based on scipy curve_fit function). 
This will be simple trainer that based on only single main feature of the group, for example, `bpf_cpu_time_us` of BPFOnly group. 

On Trainer instance creation, fit_func such as logarithm func, logistic func is needed to be set.
In addition, p0 and main feature can be alternatively set via `p0_func` and `feature_index`, index of the target feature in the FeatureGroup, correspondingly.

```py
class CurveFitModel():
    def __init__(self, fit_func, p0_func=None):
        self.fit_func = fit_func
        self.popt = None
        self.pcov = None
        self.feature_index = None
        self.p0_func = p0_func
```

Signed-off-by: Sunyanan Choochotkaew <sunyanan.choochotkaew1@ibm.com>

### Why is this needed?

The main objective is to expand the range of power model training to existing data set such as [SPECPower](https://www.spec.org/cgi-bin/osgresults?conf=power_ssj2008;op=form;format=pre) where only CPU usage metric is available.

**Comment by marceloamaral** [comment]
@sunya-ch Interesting
Btw, why scikit or xgboost are not enough?

**Comment by sunya-ch** [comment]
The curvefit allows more flexibility for adding a new simple model function that based on a single independent variable not limited to what provided from the scikit.
I put my PR here: https://github.com/sustainable-computing-io/kepler-model-server/pull/215.

**Comment by rootfs** [comment]
The curve fitting algorithms can be implemented in golang for kepler without introducing additional pkg or libraries.
