### ISSUE TITLE
Docs: Missing information

### ISSUE THREAD

**Issue by hdost** [sustainable-computing-io/kepler-model-server#235]
### What happened?

When I was on https://sustainable-computing.io/kepler_model_server/node_profile/ there's a link to a profile tool which seems to have been "refactored" away.

### What did you expect to happen?

The link not to be broken and maybe an explanation about where the replacement when OR at least a better commit message to explain where to go or what to do different.

### How can we reproduce it (as minimally and precisely as possible)?

Removed here https://github.com/sustainable-computing-io/kepler-model-server/commit/b71db31dc012ddf550c77cb0b814b68bf966bd97

### Kepler image tag

<details>

</details>

### Deployment

- [ ] Model server
- [ ] Estimator
- [ ] Online trainer
- [ ] Offline trainer
- [X] Profiler

### Kepler model server image tag if deployed

<details>

</details>

### Kepler estimator image tag if deployed

<details>

</details>

### Kepler online trainer image tag if deployed

<details>

</details>

### Kepler offline trainer image tag if deployed

<details>

</details>

### Kepler profiler image tag if deployed

<details>

</details>

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Install tools

<details>

</details>

### Kepler deployment config

<details>

For on kubernetes:
```console
$ KEPLER_NAMESPACE=kepler

# provide kepler configmap
$ kubectl get configmap kepler-cfm -n ${KEPLER_NAMESPACE} 
# paste output here

# provide kepler model server configmap if Kepler Model Server is deployed 
$ kubectl get configmap kepler-model-server-cfm -n ${KEPLER_NAMESPACE} 
# paste output here

# provide kepler deployment description
$ kubectl describe deployment kepler-exporter -n ${KEPLER_NAMESPACE} 
```

For standalone:
# put your Kepler command argument here

</details>

**Comment by sunya-ch** [comment]
Thank you for reporting this issue. I pushed a PR to kepler-doc repo.
