### ISSUE TITLE
Where does the kepler_spec_power_db image come from?

### ISSUE THREAD

**Issue by dave-tucker** [sustainable-computing-io/kepler-model-server#267]
### What would you like to be added?

This model is used to train the specpower model.
However there are no instructions on how that image was built and how to update it in future.

### Why is this needed?

We should be able to audit this image so we know what it contains and when it needs to be updated.

**Comment by sunya-ch** [comment]
It is locally built locally. This image provides transformed SPECpower data which is in Kepler CPU time metric. The paper is still under submission.
