### ISSUE TITLE
0.7.7 image is rebuilt on every merge to main

### ISSUE THREAD

**Issue by sthaha** [sustainable-computing-io/kepler-model-server#275]
Versioned / tagged build 0.7.7 gets overwritten whenever main changes. 
https://quay.io/repository/sustainable_computing_io/kepler_model_server?tab=history. 

Once release has been cut, we shouldn't overwrite the published images.

**Comment by sunya-ch** [comment]
closed by https://github.com/sustainable-computing-io/kepler-model-server/pull/279 (change to latest)
We will work on better way to automate the version increment.
