### ISSUE TITLE
Broken URL in tekton/README.md

### ISSUE THREAD

**Issue by ideaship** [sustainable-computing-io/kepler-model-server#369]
### What happened?

When running the command given in https://github.com/sustainable-computing-io/kepler-model-server/blob/main/model_training/tekton/README.md, the result is:

```
error: unable to read URL "https://storage.googleapis.com/tekton-releases/pipeline/0.54.1/release.yaml", server reported 404 Not Found, status code=404
```

### What did you expect to happen?

Command to return without an error.

### How can we reproduce it (as minimally and precisely as possible)?

Using curl, no k8s cluster is needed:

```
curl https://storage.googleapis.com/tekton-releases/pipeline/0.54.1/release.yaml
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: tekton-releases/pipeline/0.54.1/release.yaml</Details></Error>
```

### Anything else we need to know?

The correct URL for the 0.54.1 release is:

```
https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.54.1/release.yaml
```

### Kepler image tag

<details>

</details>

### Deployment

- [ ] Model server
- [ ] Estimator
- [ ] Online trainer
- [ ] Offline trainer
- [ ] Profiler

### Kepler model server image tag if deployed

<details>

</details>

### Kepler estimator image tag if deployed

<details>

</details>

### Kepler online trainer image tag if deployed

<details>

</details>

### Kepler offline trainer image tag if deployed

<details>

</details>

### Kepler profiler image tag if deployed

<details>

</details>

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Install tools

<details>

</details>

### Kepler deployment config

<details>

For on kubernetes:
```console
$ KEPLER_NAMESPACE=kepler

# provide kepler configmap
$ kubectl get configmap kepler-cfm -n ${KEPLER_NAMESPACE} 
# paste output here

# provide kepler model server configmap if Kepler Model Server is deployed 
$ kubectl get configmap kepler-model-server-cfm -n ${KEPLER_NAMESPACE} 
# paste output here

# provide kepler deployment description
$ kubectl describe deployment kepler-exporter -n ${KEPLER_NAMESPACE} 
```

For standalone:
# put your Kepler command argument here

</details>

**Comment by sunya-ch** [comment]
@ideaship Are you interested to push a PR to fix this issue?
