### ISSUE TITLE
Support Model Subscription

### ISSUE THREAD

**Issue by KaiyiLiu1234** [sustainable-computing-io/kepler-model-server#59]
The Model Server currently does not use accuracy metrics to determine whether a model is fit to be exporter for use for Kepler and the Kepler Operator. An API needs to be set up to incorporate different accuracy measures for Node and Pod Energy Models. For instance, one strategy to measure the accuracy of a model is to compare the Mean Absolute Error with the actual Energy result during the model testing phases.

**Comment by KaiyiLiu1234** [comment]
Scikit learn includes MAPE which is a good way of judging how good regression models are and is essentially like comparing the MAE with the actual energy result.

**Comment by sunya-ch** [comment]
We added the MAPE in the exported value.
