### ISSUE TITLE
ScikitMixed model training pipeline

### ISSUE THREAD

**Issue by vishnayak** [sustainable-computing-io/kepler-model-server#63]
Hello,

I couldn't find the training pipeline for ScikitMixed model for getting DynPower using Gradient Boosting Regressor, since this is the only model available for CgroupOnly features. There are a few trained model representations available in tests/test_models for ScikitMixed - is there no way to get weights trained for finding DynPower on a separately collected cgroup dataset? Please let me know if I've missed something.

Thank you

**Comment by sunya-ch** [comment]
Currently, the ScikitMixed model is trained offline. However, we can implement it as a pipeline for online training or just upload the model as well as its metadata trained by other dataset and change the [initial model config of kepler exporter](https://github.com/sustainable-computing-io/kepler/blob/7e0f5a077fe609bac40585001f9e1f553e2983d9/manifests/config/exporter/exporter.yaml#L22.) to apply that model. 

You may refer to the following code to generate the metadata of the new trained model. 
https://github.com/sustainable-computing-io/kepler-model-server/blob/10e51962d5d3a911c4b9c88f460a1cf79d6f760b/server/train/pipeline.py#L81-L92

Anyway, I think we may add the pipeline for the scikit model and also the instruction or script for the custom offline model too.
