### ISSUE TITLE
Implementing Unit and Integration Tests

### ISSUE THREAD

**Issue by KaiyiLiu1234** [sustainable-computing-io/kepler-model-server#66]
Now that Kepler has been released in v0.4 and the Model Server has been incorporated in the Kepler Operator for the next release, Unit and Integration Tests should be set up that (80% coverage).

**Comment by sunya-ch** [comment]
Track progress for this page:
https://github.com/sustainable-computing-io/kepler-model-server/tree/main/tests

**Comment by sunya-ch** [comment]
https://github.com/sustainable-computing-io/kepler/issues/505
