### ISSUE TITLE
add network metrics in models - include metrics and models for kepler standalone

### ISSUE THREAD

**Issue by rootfs** [sustainable-computing-io/kepler-model-server#68]
This is to follow https://github.com/sustainable-computing-io/kepler/issues/501

**Comment by KaiyiLiu1234** [comment]
Include irq metrics in train types and create a separate pipeline (irq metrics included in bpf)

**Comment by KaiyiLiu1234** [comment]
This should be resolved with [#80](https://github.com/sustainable-computing-io/kepler-model-server/pull/80). Changes should be made with how the model is exposed for prediction via Flask routes, however the underlying logic for online training and predicting with XGBoost Regressor is functioning.

**Comment by KaiyiLiu1234** [comment]
Will close once the XGBoost Pipeline is fully integrated with the solution for https://github.com/sustainable-computing-io/kepler-model-server/issues/75
