### ISSUE TITLE
Deploy model server on new environment and run benchmark to create models.

### ISSUE THREAD

**Issue by rootfs** [sustainable-computing-io/kepler-model-server#69]
0.5 release

**Comment by sunya-ch** [comment]
Should cover the issue https://github.com/sustainable-computing-io/kepler-model-server/issues/94

**Comment by sunya-ch** [comment]
Now simplify training step here:
https://github.com/sustainable-computing-io/kepler-model-server/tree/main/model_training 

Describe the instruction to contribute in contributing page:
https://github.com/sustainable-computing-io/kepler-model-server/blob/main/contributing.md
