### ISSUE TITLE
Set up Model Repository

### ISSUE THREAD

**Issue by KaiyiLiu1234** [sustainable-computing-io/kepler-model-server#73]
This is to follow [#1](https://github.com/sustainable-computing-io/kepler-models/issues/1)

**Comment by sunya-ch** [comment]
can it be named by `kepler-model-db`? I expected this name in the new pipeline code. https://github.com/sustainable-computing-io/kepler-model-server/pull/88

**Comment by KaiyiLiu1234** [comment]
Ok

**Comment by sunya-ch** [comment]
created [here](https://github.com/sustainable-computing-io/kepler-model-db/tree/main)
