### ISSUE TITLE
Set up pipeline models for NodeTotalModels

### ISSUE THREAD

**Issue by KaiyiLiu1234** [sustainable-computing-io/kepler-model-server#79]
Currently, no pipeline has been set up for training NodeTotalModels (Abs power model). What type of features should NodeTotalModels take into consideration and should it still follow a Regression model like the NodeComponent Models?

**Comment by sunya-ch** [comment]
This is obsoleted. Pipeline no longer has Total and Component but rather flexibly identified by energy source which are `acpi` and `rapl`.
