### ISSUE TITLE
Training Models intelligently using data from a variety of conditions to avoid overfitting

### ISSUE THREAD

**Issue by KaiyiLiu1234** [sustainable-computing-io/kepler-model-server#83]
As mentioned by Marcelo in the previous Kepler 0.5 meeting, alongside the xgboost model pipelines, we should set up special training data generated from a variety of different conditions for validating our models and ensuring the models we generate do not overfit for a specific kind of data.

**Comment by sunya-ch** [comment]
@KaiyiLiu1234 could you elaborate example of different conditions?

**Comment by sunya-ch** [comment]
discussed in community meeting, check [ppt].(https://docs.google.com/presentation/d/1G783dnDNY4roz2uGI2apgVhmozTSnxZ1/edit?usp=sharing&ouid=114970578606024250114&rtpof=true&sd=true)
