### ISSUE TITLE
Update XGBoost package power pipeline

### ISSUE THREAD

**Issue by KaiyiLiu1234** [sustainable-computing-io/kepler-model-server#86]
- XGBoost package power pipeline needs to support the following feature groups and label group:

- [ ] CGroupOnly to predict Total Package Power and Total DRAM for Node level and per container level (no isolator)

- [x] BPFOnly to predict Total Package Power for Node Level and per container level (no isolator)

- [x] Hardware Counters to predict Total Package Power and Total DRAM for Node level and per container level (no isolator)

**Comment by sunya-ch** [comment]
I guess this covered the issue https://github.com/sustainable-computing-io/kepler-model-server/issues/89.
